### PR TITLE
add Syntalos readme

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@bendichter How in depth should this ReadMe be? Should it include full tutorials on usage?

### CODE REVIEW

**Comment by bendichter** [comment]
@CodyCBakerPhD 

> convert the raw intan signals without LFP processing or spike sorting

Can we make a pipeline that has the ability to convert all of these components?

**Comment by CodyCBakerPhD** [comment]
@bendichter A one-shot script for that would require the use of the pickle interfaces however, are you OK with that? Otherwise that script is designed to include that data after a quick-save (partial NWBFile)

**Comment by bendichter** [comment]
@CodyCBakerPhD Yes I'm fine with a pickle interface. An even better solution would be if you could read from a previously created NWB file using `NwbSortingExtractor`

**Comment by CodyCBakerPhD** [comment]
@bendichter That is exactly what the current external script does. The "quick-save" makes a partial NWBFile with sorting and LFP information, the script only converts and fills in the rest

**Pull request merged**
