### PR TITLE
Fixes

### LINKED ISSUE #35: TypeError: write_recording() got an unexpected keyword argument 'write_as_lfp'
@luiztauffer  Got this error when trying to quick_write, might this be a carry-over of previous dimension error issues?

image

image

Many thanks in advance!

### LINKED ISSUE #36: Sampling Frequency mismatch
@luiztauffer Hi Luiz,

All of the recordings I have put through the pipeline so far have been 30,030Hz (3.003003003003003*10^4). The CED pipeline keeps generating a sampling rate of 30,000Hz. I'm just curious as to the origins of the difference and whether or not this is a deliberate downsampling?

Many thanks.

Ross

image
image

image
image

### PR DESCRIPTION
**Pull request by luiztauffer**
- [x] Fix #36 
- [x] Fix #35 (write_recording)
- [x] Fix `write_sorting()` (depends on https://github.com/catalystneuro/nwb-conversion-tools/issues/182)

### CODE REVIEW

**Comment by rf13734** [comment]
@luiztauffer Thanks! Apologies, I could not attend to this yesterday. I will now!

**Comment by luiztauffer** [comment]
this should be good to merge, can you take a look @alejoe91 @CodyCBakerPhD ?

**Comment by alejoe91** [comment]
@luiztauffer looks good to me. Can you clean up the notebook before merging?

**Comment by luiztauffer** [comment]
@alejoe91 done

**Review by alejoe91 — APPROVED** [review]

**Pull request merged**
