### PR TITLE
separating notebook improvements to different PR

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@bendichter Easiest way to view these changes would just be the [direct notebook ](https://github.com/catalystneuro/mease-lab-to-nwb/blob/pipeline_conversion_improvements/notebooks/syntalos_spikeinterface_pipeline.ipynb)

Main changes are addition of two sections to end of pipeline

1. Quick save option; requires session description, some chosen sorting extractor, and then writes the minimal information from the notebook using a single operation. To complete the full conversion, user must use external script after the notebook file has completed creating the NWBFile

2. Full save option; essentially the code of the external script, but formatted in an even more slightly user friendly way. First cell involves all user-specific metainfo required for full conversion, second cell performs full run of both local environment objects as well as external files sources

### CODE REVIEW

**Comment by bendichter** [comment]
Looks good, as soon as we settle on the location of `quick_save`

**Comment by CodyCBakerPhD** [comment]
Updated with non-static usage of quick_write

**Comment by alejoe91** [comment]
Looks good to me @CodyCBakerPhD

**Comment by CodyCBakerPhD** [comment]
@bendichter Good to merge?

**Pull request merged**
